version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.1
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/templates:/usr/share/logstash/templates
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    environment:
      - MONGODB_URI=${MONGODB_URI}
    command: >
      bash -c "
        bin/logstash-plugin install logstash-input-mongodb &&
        bin/logstash
      "
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "5044:5044"

  kibana:
    build:
      context: .
      dockerfile: Dockerfile.kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy

volumes:
  elasticsearch_data: